# Generated by Django 4.0.6 on 2022-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = Tru

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
