# Generated by Django 4.0.6 on 2022-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programmingLanguage',
            field=models.TextField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('Visual Basic', 'Visual Basic')], default='NO INFO', null=True),
        ),
    ]
